version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/postgresql/data

  flask_app:
    build:
      context: ./app
    networks:
      - my_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask_app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data: